# Generated by Django 2.2.4 on 2019-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
